add hack to be able to run tests with IntelliJ test runner
otherwise we get `NoClassDefFoundErrors` when running the tests. Unfortunately the project does not seem to build anymore at all with IntelliJ 2020.1 and Gradle 6, but delegating the build to Gradle and running the tests with the IntelliJ test runner seems a fair compromise to me (so far I have not been a fan of delegating running the tests to Gradle, because it takes longer and considers Gradle configurations which can lead to strange behavior, e.g. if a tag is filtered by default but you want to run a test that is tagged).
I have analysed the `iml` files generated by IntelliJ and do not completely understand the behavior. For example `archunit-junit5-engine` receives an entry for a `testRuntime` dependency to `ASM`, but `archunit-junit4` does not. So far it seems like tests from all other modules besides `archunit-junit4` are configured correctly and can thus be run with the IntelliJ test runner, so this seems to be the last thing necessary to be able to work reasonably well with the project within IntelliJ.

Signed-off-by: Peter Gafert <peter.gafert@tngtech.com>